// backend/data.js
const mockInteractions = [
  { appraiser: null, id: "int-a8b-001", analyst: "Marcos da Silva Mendonça", time: 42 },
  { appraiser: null, id: "int-c2d-002", analyst: "Ana Carolina Oliveira", time: 75 },
  { appraiser: null, id: "int-f9e-003", analyst: "João Pedro Santos", time: 55 },
  { appraiser: null, id: "int-g7h-004", analyst: "Beatriz Lima Ferreira", time: 98 },
  { appraiser: null, id: "int-j4k-005", analyst: "Lucas Costa Pereira", time: 38 },
  { appraiser: null, id: "int-m1n-006", analyst: "Fernanda Alves Rodrigues", time: 61 },
  { appraiser: null, id: "int-p8q-007", analyst: "Carlos Eduardo Souza", time: 110 },
  { appraiser: null, id: "int-r5s-008", analyst: "Júlia Ribeiro Martins", time: 82 },
  { appraiser: null, id: "int-t2u-009", analyst: "Rafael Azevedo Gomes", time: 45 },
  { appraiser: null, id: "int-v9w-010", analyst: "Gabriela Dias Barbosa", time: 36 },
  { appraiser: null, id: "int-x6y-011", analyst: "Matheus Correia Nunes", time: 50 },
  { appraiser: null, id: "int-z3a-012", analyst: "Larissa Fernandes Araujo", time: 92 },
  { appraiser: null, id: "int-b0c-013", analyst: "Thiago Moreira Carvalho", time: 70 },
  { appraiser: null, id: "int-d7e-014", analyst: "Amanda Pinto Castro", time: 48 },
  { appraiser: null, id: "int-f4g-015", analyst: "Bruno Monteiro Barros", time: 65 },
  { appraiser: null, id: "int-h1j-016", analyst: "Marcos da Silva Mendonça", time: 105 },
  { appraiser: null, id: "int-k8l-017", analyst: "Ana Carolina Oliveira", time: 41 },
  { appraiser: null, id: "int-m5n-018", analyst: "João Pedro Santos", time: 58 },
  { appraiser: null, id: "int-p2q-019", analyst: "Beatriz Lima Ferreira", time: 88 },
  { appraiser: null, id: "int-r9s-020", analyst: "Lucas Costa Pereira", time: 72 },
  { appraiser: null, id: "int-t6u-021", analyst: "Fernanda Alves Rodrigues", time: 115 },
  { appraiser: null, id: "int-v3w-022", analyst: "Carlos Eduardo Souza", time: 39 },
  { appraiser: null, id: "int-x0y-023", analyst: "Júlia Ribeiro Martins", time: 53 },
  { appraiser: null, id: "int-z7a-024", analyst: "Rafael Azevedo Gomes", time: 68 },
  { appraiser: null, id: "int-b4c-025", analyst: "Gabriela Dias Barbosa", time: 95 },
  { appraiser: null, id: "int-d1e-026", analyst: "Matheus Correia Nunes", time: 120 },
  { appraiser: null, id: "int-f8g-027", analyst: "Larissa Fernandes Araujo", time: 47 },
  { appraiser: null, id: "int-h5j-028", analyst: "Thiago Moreira Carvalho", time: 85 },
  { appraiser: null, id: "int-k2l-029", analyst: "Amanda Pinto Castro", time: 40 },
  { appraiser: null, id: "int-m9n-030", analyst: "Bruno Monteiro Barros", time: 78 },
  { appraiser: null, id: "int-p6q-031", analyst: "Marcos da Silva Mendonça", time: 62 },
  { appraiser: null, id: "int-r3s-032", analyst: "Ana Carolina Oliveira", time: 91 },
  { appraiser: null, id: "int-t0u-033", analyst: "João Pedro Santos", time: 51 },
  { appraiser: null, id: "int-v7w-034", analyst: "Beatriz Lima Ferreira", time: 83 },
  { appraiser: null, id: "int-x4y-035", analyst: "Lucas Costa Pereira", time: 44 },
];

module.exports = { mockInteractions };